# Generated by Django 3.1.5 on 2021-01-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='일기의 제목')),
                ('content', models.TextField(verbose_name='일기의 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='일기를 쓴 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='일기를 수정한 시간')),
            ],
        ),
    ]
